package by.tsarenkov.shop.controller;

public enum CommandName {
    LOGIN,
    GOTOPERSONALPAGE,
    GOTOREGISTRATIONPAGE,
    REGISTRATION,
    SAVENEWUSER,
    GOTOMAINPAGE,
    ACTIVATION,
    CHANGELANGUAGE,
    SAVENEWPRODUCT,
    GOTOPRODUCTPAGE,
    PRODUCTVIEW,
    SAVEPRODUCTINBASKET,
    DELETEPRODUCTFROMBASKET,
    GOTOBASKETPAGE,
    GOTOPAGE,
    PARTICULAREBOOKVIEW,
    CHANGEEBOOK,
    SAVECHANGEDEBOOK,
    CHANGELAPTOP,
    CHANGETABLET,
    CHANGESMARTPHONE
}
