package by.tsarenkov.shop.controller;

public enum CommandName {
    LOGIN,
    GOTOPERSONALPAGE,
    GOTOREGISTRATIONPAGE,
    REGISTRATION,
    SAVENEWUSER,
    GOTOMAINPAGE,
    ACTIVATION,
    CHANGELANGUAGE,
    SAVENEWPRODUCT,
    GOTOPRODUCTPAGE,
    EBOOKVIEW,
    SAVEPRODUCTINBASKET,
    DELETEPRODUCTINBASKET,
    BASKETVIEW
}
